# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:                       berlin_format # feel free to change the mode to yeti_format. (Don't forget to change the validation function)

pollutants:                 [PollutantType.NOx]

strategy:                   code.copert_strategy.CopertStrategy.CopertStrategy
load_berlin_format_data_function:   code.copert_strategy.load_berlin_format_data.load_copert_berlin_format_data
load_yeti_format_data_function: code.copert_strategy.load_yeti_format_data.load_copert_yeti_format_data
validation_function:        code.copert_hot_fixed_speed_strategy.validate.validate_copert_fixed_speed_berlin_format_files

# -------- file names -----------

berlin_format_link_data:            example/example_berlin_format_data/link_data_with_speed.csv
berlin_format_fleet_composition:    example/example_berlin_format_data/fleet_composition.csv
berlin_format_emission_factors:     example/example_berlin_format_data/copert_emission_factors.csv
berlin_format_los_speeds:           example/example_berlin_format_data/los_speeds.csv
berlin_format_traffic_data:         example/example_berlin_format_data/traffic_data.csv
berlin_format_vehicle_mapping:      example/example_berlin_format_data/vehicle_mapping.csv
berlin_format_nh3_emission_factors: example/example_berlin_format_data/nh3_tier2_emission_factors.csv
berlin_format_nh3_mapping:          example/example_berlin_format_data/nh3_mapping.csv

yeti_format_emission_factors:   example/example_yeti_format_data/copert_emission_factors.csv
yeti_format_los_speeds:         example/example_yeti_format_data/los_speeds.csv
yeti_format_vehicle_data:       example/example_yeti_format_data/vehicle_data.csv
yeti_format_link_data:          example/example_yeti_format_data/link_data_with_speed.csv
yeti_format_traffic_data:       example/example_yeti_format_data/traffic_data.csv

# -------- output folder(s) --------------

output_folder:              example_output_copert_hot_fixed_speed

# Optional parameter, only relevant for mode berlin_format:
# output_folder_for_yeti_format_data:     yeti_format_data_new

# -------- strategy specific arguments -----------

# Include the following line to use a global speed value
# v:                          30

use_nh3_tier2_ef:           yes
only_hot:                   yes
fixed_speed:                yes

# -------- optional arguments ------------

# links_to_use:               [link_a]
# use_n_traffic_data_rows:    100