# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:                       input_data  # feel free to change the mode to unified_data

pollutant:                  PollutantType.NOx
strategy:                   code.copert_hot_fixed_speed_strategy.CopertHotFixedSpeedStrategy.CopertHotFixedSpeedStrategy
load_input_data_function:   code.copert_hot_fixed_speed_strategy.load_input_data.load_copert_fixed_speed_input_data
load_unified_data_function: code.copert_hot_fixed_speed_strategy.load_unified_data.load_copert_fixed_speed_unified_data

output_folder:              example_output_copert_hot

# -------- file names -----------

input_link_data:            example/example_input_data/link_data_with_speed.csv
input_fleet_composition:    example/example_input_data/fleet_composition.csv
input_emission_factors:     example/example_input_data/copert_emission_factors.csv
input_los_speeds:           example/example_input_data/los_speeds.csv
input_traffic_data:         example/example_input_data/traffic_data.csv
input_vehicle_mapping:      example/example_input_data/vehicle_mapping.csv
input_nh3_emission_factors: example/example_input_data/nh3_tier2_emission_factors.csv
input_nh3_mapping:          example/example_input_data/nh3_mapping.csv

unified_emission_factors:   example/example_unified_data/copert_emission_factors.csv
unified_los_speeds:         example/example_unified_data/los_speeds.csv
unified_vehicle_data:       example/example_unified_data/vehicle_data.csv
unified_link_data:          example/example_unified_data/link_data_with_speed.csv
unified_traffic_data:       example/example_unified_data/traffic_data.csv

# -------- strategy specific parameters -----------

# Include the following line to use a global speed value
# v:                          30

use_nh3_tier2_ef:           yes