# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:                       input_data  # feel free to change the mode to unified_data

pollutant:                  PollutantType.CO
strategy:                   code.copert_cold_strategy.CopertColdStrategy.CopertColdStrategy
load_input_data_function:   code.copert_cold_strategy.load_input_data.load_copert_cold_input_data
load_unified_data_function: code.copert_cold_strategy.load_unified_data.load_copert_cold_unified_data

output_folder:              example_output_copert_cold
# output_folder_for_unified_data: unified_data_new

# -------- file names -----------

input_link_data:            example/example_input_data/link_data.csv
input_fleet_composition:    example/example_input_data/fleet_composition.csv
input_emission_factors:     example/example_input_data/copert_emission_factors.csv
input_los_speeds:           example/example_input_data/los_speeds.csv
input_traffic_data:         example/example_input_data/traffic_data.csv
input_vehicle_mapping:      example/example_input_data/vehicle_mapping.csv
input_cold_ef_table:        example/example_input_data/cold_emission_factors.csv

unified_emission_factors:   example/example_unified_data/copert_emission_factors.csv
unified_los_speeds:         example/example_unified_data/los_speeds.csv
unified_vehicle_data:       example/example_unified_data/vehicle_data.csv
unified_link_data:          example/example_unified_data/link_data.csv
unified_traffic_data:       example/example_unified_data/traffic_data.csv
unified_cold_ef_table:      example/example_unified_data/cold_emission_factors.csv
unified_vehicle_mapping:    example/example_unified_data/vehicle_mapping.csv

# -------- strategy specific parameters -----------

use_nh3_tier2_ef:           no
exclude_road_types:         [MW_City]
exclude_area_types:         [Rural]

ltrip:                      12
temperature:                15