# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:                       input_data  # feel free to change the mode to unified_data

pollutant:                  PollutantType.NOx
strategy:                   code.hbefa_hot_strategy.HbefaHotStrategy.HbefaHotStrategy
load_input_data_function:   code.hbefa_hot_strategy.load_input_data.load_hbefa_input_data
load_unified_data_function: code.hbefa_hot_strategy.load_unified_data.load_hbefa_unified_data

# If you change the mode to unified_data, don't set a validation function (delete the following line).
validation_function:        code.hbefa_hot_strategy.validate.validate_hbefa_input_files

output_folder:              example_output_hbefa_hot

# -------- file names -----------

input_link_data:            example/example_input_data/link_data.csv
input_fleet_composition:    example/example_input_data/fleet_composition.csv
input_emission_factors:     example/example_input_data/hbefa_emission_factors.csv
input_traffic_data:         example/example_input_data/traffic_data.csv

unified_emission_factors:   example/example_unified_data/hbefa_emission_factors.csv
unified_vehicle_data:       example/example_unified_data/vehicle_data.csv
unified_link_data:          example/example_unified_data/link_data.csv
unified_traffic_data:       example/example_unified_data/traffic_data.csv