# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:           berlin_format  # feel free to change the mode to yeti_format. (Don't forget to change the validation function)

pollutants:                 [PollutantType.NOx]
strategy:                   code.hbefa_cold_strategy.HbefaColdStrategy.HbefaColdStrategy
load_berlin_format_data_function:   code.hbefa_cold_strategy.load_berlin_format_data.load_hbefa_cold_berlin_format_data
load_yeti_format_data_function: code.hbefa_cold_strategy.load_yeti_format_data.load_hbefa_cold_yeti_format_data

output_folder:              example_output_hbefa_cold

# -------- file names -----------

berlin_format_link_data:            example/example_berlin_format_data/link_data.csv
berlin_format_fleet_composition:    example/example_berlin_format_data/fleet_composition.csv
berlin_format_emission_factors:     example/example_berlin_format_data/hbefa_cold_start_emission_factors.csv
berlin_format_cold_starts_data:     example/example_berlin_format_data/cold_starts.csv

yeti_format_emission_factors:   example/example_yeti_format_data/hbefa_cold_start_emission_factors.csv
yeti_format_vehicle_data:       example/example_yeti_format_data/vehicle_data.csv
yeti_format_link_data:          example/example_yeti_format_data/link_data.csv
yeti_format_cold_starts_data:   example/example_yeti_format_data/cold_starts_data.csv