# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:                       input_data  # feel free to change the mode to unified_data. (Don't forget to change the validation function)

pollutants:                 [PollutantType.NOx]
strategy:                   code.hbefa_cold_strategy.HbefaColdStrategy.HbefaColdStrategy
load_input_data_function:   code.hbefa_cold_strategy.load_input_data.load_hbefa_cold_input_data
load_unified_data_function: code.hbefa_cold_strategy.load_unified_data.load_hbefa_cold_unified_data
#validation_function:        code.hbefa_cold_strategy.validate.validate_hbefa_input_files

output_folder:              example_output_hbefa_cold

# -------- file names -----------

input_link_data:            example/example_input_data/link_data.csv
input_fleet_composition:    example/example_input_data/fleet_composition.csv
input_emission_factors:     example/example_input_data/hbefa_cold_start_emission_factors.csv
input_cold_starts_data:     example/example_input_data/cold_starts.csv

unified_emission_factors:   example/example_unified_data/hbefa_cold_start_emission_factors.csv
unified_vehicle_data:       example/example_unified_data/vehicle_data.csv
unified_link_data:          example/example_unified_data/link_data.csv
unified_cold_starts_data:   example/example_unified_data/cold_starts_data.csv