# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:           berlin_format  # feel free to change the mode to yeti_format. (Don't forget to change the validation function)

pollutants:                 [PollutantType.PM_Non_Exhaust]

strategy:                   code.pm_non_exhaust_strategy.PMNonExhaustStrategy.PMNonExhaustStrategy
load_berlin_format_data_function:   code.pm_non_exhaust_strategy.load_berlin_format_data.load_pm_non_exhaust_berlin_format_data
load_yeti_format_data_function: code.pm_non_exhaust_strategy.load_yeti_format_data.load_pm_non_exhaust_yeti_format_data
validation_function:        code.pm_non_exhaust_strategy.validate.validate_pm_non_exhaust_berlin_format_files

# -------- file names -----------

berlin_format_link_data:            example/example_berlin_format_data/link_data.csv
berlin_format_fleet_composition:    example/example_berlin_format_data/fleet_composition.csv
berlin_format_los_speeds:           example/example_berlin_format_data/los_speeds.csv
berlin_format_traffic_data:         example/example_berlin_format_data/traffic_data.csv

yeti_format_link_data:          example/example_yeti_format_data/link_data.csv
yeti_format_vehicle_data:       example/example_yeti_format_data/vehicle_data.csv
yeti_format_los_speeds:         example/example_yeti_format_data/los_speeds.csv
yeti_format_traffic_data:       example/example_yeti_format_data/traffic_data.csv

# -------- output folder(s) --------------

output_folder:              example_output_pm_non_exhaust

# Optional parameter, only relevant for mode berlin_format:
# output_folder_for_yeti_format_data:     yeti_format_data_new

# -------- strategy specific arguments -----------

load_factor:                0.3

# -------- optional arguments ------------

# links_to_use:               [link_a]
# use_n_traffic_data_rows:    100