# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:                       input_data  # feel free to change the mode to unified_data

pollutant:                  PollutantType.PM_Non_Exhaust
strategy:                   code.pm_non_exhaust_strategy.PMNonExhaustStrategy.PMNonExhaustStrategy
load_input_data_function:        code.pm_non_exhaust_strategy.load_input_data.load_pm_non_exhaust_input_data
load_unified_data_function:      code.pm_non_exhaust_strategy.load_unified_data.load_pm_non_exhaust_unified_data

output_folder:              example_output_pm_non_exhaust

# -------- file names -----------

input_link_data:            example/example_input_data/link_data.csv
input_fleet_composition:    example/example_input_data/fleet_composition.csv
input_los_speeds:           example/example_input_data/los_speeds.csv
input_traffic_data:         example/example_input_data/traffic_data.csv

unified_link_data:          example/example_unified_data/link_data.csv
unified_vehicle_data:       example/example_unified_data/vehicle_data.csv
unified_los_speeds:         example/example_unified_data/los_speeds.csv
unified_traffic_data:       example/example_unified_data/traffic_data.csv

# -------- strategy specific parameters -----------

load_factor:                0.3