# This is a configuration file for the YETI model

# -------- run configurations ----------

mode:                       input_data  # feel free to change the mode to unified_data

pollutant:                  PollutantType.NOx
strategy:                   code.copert_hot_strategy.CopertHotStrategy.CopertHotStrategy
load_input_data_function:   code.copert_hot_strategy.load_input_data.load_copert_input_data
load_unified_data_function: code.copert_hot_strategy.load_unified_data.load_copert_unified_data

# If you change the mode to unified_data, set the validation function to code.copert_hot_strategy.validate.file_paths_are_valid:
# validation_function:        code.copert_hot_strategy.validate.file_paths_are_valid
validation_function:        code.copert_hot_strategy.validate.validate_copert_input_files

output_folder:              example_output_copert_hot

# -------- file names -----------

input_link_data:            ../data/link_data.csv
input_fleet_composition:    ../data/fleet_composition_data.csv
input_emission_factors:     ../data/copert_emission_factors.csv
input_los_speeds:           ../data/los_speeds_data.csv
input_traffic_data:         ../data/traffic_data.csv
input_vehicle_mapping:      ../data/mapping_data.csv

unified_emission_factors:   example/example_unified_data/copert_emission_factors.csv
unified_los_speeds:         example/example_unified_data/los_speeds.csv
unified_vehicle_data:       example/example_unified_data/vehicle_data.csv
unified_link_data:          example/example_unified_data/link_data.csv
unified_traffic_data:       example/example_unified_data/traffic_data.csv

# -------- strategy specific parameters -----------

use_nh3_tier2_ef:           no
use_n_traffic_data_rows:    2
